# Week 3 ML 
## Day:1 Aug 22 2022 

Computing gradients with numpy

In [ ]:
!pip install numdifftools

In [16]:
import numdifftools as nd

def f1(x):
    return x**2 + 2*x + 1
grad = nd.Gradient(f1)([2])
print(grad)

5.9999999999999964


In [4]:
import numdifftools as nd

def f1(x,y,z):
    return (x + y) * z 
grad = nd.Gradient(f1)([-2],[5],[-4])
print(grad)

-3.9999999999999503


torch basics

In [18]:
import torch
import math

In [17]:
x = torch.empty(3, 4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[1.6383e-35, 0.0000e+00, 3.3631e-44, 0.0000e+00],
        [       nan, 0.0000e+00, 1.1578e+27, 1.1362e+30],
        [7.1547e+22, 4.5828e+30, 1.2121e+04, 7.1846e+22]])


In [19]:
zeros = torch.zeros(2, 3)
print(zeros)

ones = torch.ones(2, 3)
print(ones)

torch.manual_seed(1729)
random = torch.rand(2, 3)
print(random)

torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


In [20]:
x = torch.empty(2, 2, 3)
print(x.shape)
print(x)

empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([2, 2, 3])
tensor([[[1.6384e-35, 0.0000e+00, 3.0867e-01],
         [7.3580e-02, 4.2160e-01, 6.9054e-02]],

        [[1.5002e-35, 0.0000e+00, 1.5011e-35],
         [0.0000e+00, 1.5004e-35, 0.0000e+00]]])
torch.Size([2, 2, 3])
tensor([[[1.6384e-35, 0.0000e+00, 3.3631e-44],
         [0.0000e+00,        nan, 6.9054e-02]],

        [[1.1578e+27, 1.1362e+30, 7.1547e+22],
         [4.5828e+30, 1.2121e+04, 7.1846e+22]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
tensor([[[0.2332, 0.4047, 0.2162],
         [0.9927, 0.4128, 0.5938]],

        [[0.6128, 0.1519, 0.0453],
         [0.5035, 0.9978, 0.3884]]])


In [21]:
integer_tensor = torch.tensor(((2, 4, 6), [3, 6, 9]))
print(integer_tensor)

tensor([[2, 4, 6],
        [3, 6, 9]])


Auto grad

backward : Computes the sum of gradients of given tensors with respect to graph leaves.

grad : Computes and returns the sum of gradients of outputs with respect to the inputs.


Tensor autograd functions

torch.Tensor.grad: This attribute is None by default and becomes a Tensor the first time a call to backward() computes gradients for self.

torch.Tensor.requires_grad: Is True if gradients need to be computed for this Tensor, False otherwise.

torch.Tensor.is_leaf: All Tensors that have requires_grad which is False will be leaf Tensors by convention.

torch.Tensor.backward([gradient, …]) : Computes the gradient of current tensor w.r.t.

torch.Tensor.detach: Returns a new Tensor, detached from the current graph.

torch.Tensor.detach_: Detaches the Tensor from the graph that created it, making it a leaf.

torch.Tensor.register_hook(hook): Registers a backward hook.

torch.Tensor.retain_grad(): Enables this Tensor to have their grad populated during backward().



For scalar values 

In [6]:

import torch

x = torch.tensor(2.0, requires_grad = True)

print("x:", x)

y = x**2 + 2*x + 1
print("y:", y)

y.backward()

dx = x.grad
print("x.grad :", int(dx))

x: tensor(2., requires_grad=True)
y: tensor(9., grad_fn=<AddBackward0>)
x.grad : 6


In [13]:
# importing libraries
import torch
from torch.autograd import Variable

# packing the tensors with Variable
x = Variable(torch.tensor(2.), requires_grad=True)

print("x:", x)

y = x**2 + 2*x + 1

print('Y value is:', y)

y.backward()
print("x.grad",x.grad)

x: tensor(2., requires_grad=True)
Y value is: tensor(9., grad_fn=<AddBackward0>)
x.grad tensor(6.)


For vector values:

In [25]:
import torch

x = torch.tensor([2., 3.], requires_grad=True)
y = x**2 + 2*x + 1
external_grad = torch.tensor([1., 1.])
y.backward(gradient=external_grad)
print(x.grad)

tensor([6., 8.])


For tensor values:

In [27]:
import torch

x = torch.tensor(([2., 3.],[1.,3.]), requires_grad=True)
y = x**2 + 2*x + 1
external_grad = torch.tensor(([1., 1.],[1.,1.]))
y.backward(gradient=external_grad)
print(x.grad)

tensor([[6., 8.],
        [4., 8.]])
